Creation of the ros wrapper
socrob/face_classification pull request #1
Opened 2018-05-24 13:48 UTC by miguelvidex

Based on the demo "video_emotion_gender_demo.py" this is a ROS node to use this application for face classification.

2018-05-25 00:02 UTC, ghost requested changes

2018-05-25 00:02 UTC, socrob commented on CMakeLists.txt
> +	face_classification_single.msg
Please follow the [ROS naming conventions](http://wiki.ros.org/ROS/Patterns/Conventions#Messages).

FaceClassification + FaceClassificationArray

2018-05-25 00:02 UTC, socrob commented on package.xml
> + TODO!
Add description

2018-05-25 00:02 UTC, socrob commented on ros/doc/README.md
> +mbot_face_classification documentation
Remove file

2018-05-25 00:02 UTC, socrob commented on ros/config/config_face_classification.yaml
> +# TODO!!
Remove file if unused

2018-05-25 00:02 UTC, socrob commented on package.xml
> +
Please add dependencies here and CMakeLists or make a note to add in the near future.

2018-05-25 00:02 UTC, socrob commented on CMakeLists.txt
> +	face_classification_single.msg
Please adhere to the [ROS naming conventions](http://wiki.ros.org/ROS/Patterns/Conventions#Messages) e.g. FaceClassification and FaceClassificationArray

2018-05-25 00:02 UTC, socrob commented on CMakeLists.txt
> +  face_classification_buffered.srv
Also naming conventions here

2018-05-25 00:02 UTC, socrob commented on package.xml
> + TODO!
Add description

2018-05-25 00:02 UTC, socrob commented on package.xml
> +
Add dependencies + in CMakeLists

2018-05-25 00:02 UTC, socrob commented on ros/config/config_face_classification.yaml
> +# TODO!!
Remove if unused

2018-05-25 00:02 UTC, socrob commented on ros/doc/README.md
> +mbot_face_classification documentation
Remove file

2018-05-25 00:02 UTC, socrob commented on package.xml
> + TODO!
Add a small README file, outside of ros directory. With dependencies and quick installation instructions and how to run.

2018-05-25 00:03 UTC, socrob commented on package.xml
> + TODO!
Unrelated to this file but the comment is relevant.

2018-05-25 14:49 UTC, miguelvidex commented
Can you give me some feedback about node structure? 
https://github.com/miguelvidex/face_classification/blob/master/ros/src/face_classification_ros/face_classification_node.py

And I already did some changes related to what you commented, take a look if possible.

2018-05-28 09:53 UTC, socrob commented on CMakeLists.txt
> +  std_msgs
Fix indentation, also line 9

2018-05-28 09:53 UTC, socrob commented on CMakeLists.txt
>    face_classification_continuous.srv
Make the same changes for .srv that you did for .msg, as discussed.

2018-05-28 10:24 UTC, guilhermelawless requested changes
Full review of the node.

2018-05-28 10:24 UTC, guilhermelawless commented on ros/src/face_classification_ros/face_classification_node.py
> +    self.rospack = rospkg.RosPack()
Doesn't need to be `self`

2018-05-28 10:24 UTC, guilhermelawless commented on ros/src/face_classification_ros/face_classification_node.py
> +    faces_array.header=Header()
No need for this, above line already creates the Header object.

2018-05-28 10:24 UTC, guilhermelawless commented on ros/src/face_classification_ros/face_classification_node.py
> +      new_face.id=idx_face+1
I think we should use 0-indexed as seen in object detection wrappers. Also applies to line 208.

2018-05-28 10:28 UTC, guilhermelawless commented
@miguelvidex  i have been thinking more of the best solution to sync the output msg to the input image. Let's imagine detection takes around 5 seconds (not the case of course).

Right now the output msg has a header with `rospy.Time.now()` stamp. I believe this is correct. However, how can the subscribing node know to which image this detection corresponds? I think my previous idea of using the image stamp is bad because in cases of ROS Bag replays, it will be there before it should (5s delay won't be there).

I think the best approach is the one taken here: https://github.com/leggedrobotics/darknet_ros/blob/master/darknet_ros_msgs/msg/BoundingBoxes.msg , i.e., use another field with the corresponding input image header. This should be only for the Array msg.

Do you agree with this approach?

2018-05-28 18:45 UTC, merged